#version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - /var/www/kittygram/b_static:/app/backend_static
      - /var/www/kittygram/b_media:/app/media

  frontend:
    build: ./frontend
    env_file: .env
    volumes:
      - static:/frontend_static

  gateway:
    build: ./nginx
    env_file: .env
    ports:
      - 3030:80
    volumes:
      - /var/www/kittygram/b_static:/var/www/kittygram/b_static
      - /var/www/kittygram/b_media:/var/www/kittygram/b_media
