version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: s1ngle0f/kittygram_backend
    env_file: .env
    volumes:
      - /var/www/kittygram/b_static:/app/backend_static
      - /var/www/kittygram/b_media:/app/media
    depends_on:
      - db 

  frontend:
    image: s1ngle0f/kittygram_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: s1ngle0f/kittygram_gateway
    env_file: .env
    ports:
      - 3030:80
    volumes:
      - /var/www/kittygram/b_static:/var/www/kittygram/b_static
      - /var/www/kittygram/b_media:/var/www/kittygram/b_media
    depends_on:
      - frontend
      - backend
