version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: s1ngle0f/kittygram_backend
    env_file: .env
    volumes:
      - /var/www/kittygram/static:/app/collected_static
      - /var/www/kittygram/media:/app/media
    depends_on:
      - db 

  frontend:
    image: s1ngle0f/kittygram_frontend
    env_file: .env
#    command: cp -r /app/build/. /static/
    volumes:
      - /var/www/kittygram/static:/frontend_static
    ports:
      - "3000:9000"  # Пробрасываем порт 9000 на порт 3000 хоста
    depends_on:
      - backend

  gateway:
    image: s1ngle0f/kittygram_gateway
    env_file: .env
    volumes:
      - /var/www/kittygram/static:/static/
      - /var/www/kittygram/media:/media/
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80